---
title: "Comparaciones"
author: "Santiago Muriel"
date: "20/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gridExtra)
```

Cargamos los datos
```{r}
df <- read.csv("Data/BD.csv", header = TRUE)

# Asignación de variables
Poblacion <- df$Pob 
Superficie <- df$km2
Sol.desempleo <- df$Sol_des
PEA <- df$PEA
Casos <- df$Casos_C19
Delegaciones <- as.vector(df$Alc)
```

Ajustamos los nombres de las delegaciones para poderlos graficar
```{r}
# Recortamos los nombres largos
Delegaciones[1] <- "Álvaro Obr."
Delegaciones[3] <- "Benito Jua."
Delegaciones[5] <- "Cuajimalpa"
Delegaciones[7] <- "Gustavo A.M."
Delegaciones[10] <- "Magda. Cont."
Delegaciones[11] <- "Miguel Hid."
Delegaciones[15] <- "Venust. Carr."
```


Comparaciones del índice
```{r}
# indice de vulnerabilidad
indice <- c(4.2369847,3.1202693,3.7918290,8.8090276,4.0816771,1.0867166,14.6877406,10.3079868,14.8863182,17.3828798,0.9210095,24.6801129,18.2513107,8.7275107,7.7044839,15.3095190)

# Graficamos el índice vs Sol. Desempleo/PEA 
par(mar = c(6,5,2,5))
plot(indice, col = "blue", main = "Índice vs Desempleo Covid-19", xlab = "", ylab = "índice", type = "b", xaxt = "n")
axis(side = 1, at = 1:16, labels = Delegaciones, las = 2, cex.axis = .8)
par(new = T)
plot(Sol.desempleo/PEA, col = "red", axes=F, xlab=NA, ylab=NA, type = "b")
axis(side = 4)
mtext(side = 4, line = 3, 'Solicitudes Desempleo %',)
legend("topleft",legend=c("índice", "Solicitudes"), lty=c(0,0), pch=c(16, 16), col=c("blue", "red"))

# Graficamos el índice vs Sol. Casos confirmado/Poblacion
par(mar = c(6,5,2,5))
plot(indice, col = "blue", main = "Índice vs Contagios Covid-19", xlab = "", ylab = "índice", type = "b", xaxt = "n")
axis(side = 1, at = 1:16, labels = Delegaciones, las = 2, cex.axis = .8)
par(new = T)
plot(Casos/Poblacion, col = "red", axes=F, xlab=NA, ylab=NA, type = "b")
axis(side = 4)
mtext(side = 4, line = 3, '% de la población contagiada')
legend("topleft",legend=c("índice", "Casos"), lty=c(0,0), pch=c(16, 16), col=c("blue", "red"))
```

